### ISSUE TITLE
Expired Discord Link

### ISSUE THREAD

**Issue by raj23689** [Exodia-OS/exodia-releases#1]
I have shared the link of your repo to Axyl OS discord community, and someone there has shown interest in testing the OS builds, but has informed me that your discord links have expired.

So if you have any discord link please share the link so that I can share that link to the concerned person.

- - Thank you  and keep working on OS.

**Comment by mmsaeed509** [comment]
sorry for the late response @raj23689 
join [discord](https://discord.gg/wPDyfR5AV9)

**Comment by raj23689** [comment]
> sorry for the late response @raj23689 
> join [discord](https://discord.gg/wPDyfR5AV9)

Thanks
